##
## EPITECH PROJECT, 2021
## B-OOP-400-MPL-4-1-arcade-corentin.petrau
## File description:
## Makefile
##

all:
	-mkdir ../lib/
	make -C ./Pacman
	make -C ./Snake

clean:
	make clean -C ./Pacman
	make clean -C ./Snake

fclean: clean
	make fclean -C ./Pacman
	make fclean -C ./Snake

re: fclean all