#!/usr/bin/env python3

import sys
import math


if len(sys.argv) == 2 and str(sys.argv[1]) == "-h":
    print("USAGE\n    ./103cipher message key flag\n")
    print("DESCRIPTION\n    message\ta message, made of ASCII characters")
    print("    key \tthe encryption key, made of ASCII characters")
    print("    flag\t0 for the message to be encrypted, 1 to be encrypted")
    sys.exit(0)
try:
    xo = str(sys.argv[1])
    x1 = str(sys.argv[2])
except:
    sys.exit(84)
if len(sys.argv) != 4:
    sys.exit(84);
if sys.argv[3] == "0":
    sys.exit(0)
if (sys.argv[3] != "0"):
    sys.exit(84)